#############################################################################
#  SenseoControl 2.0                                                        #
#  Copyright (C) 2013-2018  Stefan Kalscheuer                               #
#                                                                           #
#  This program is free software: you can redistribute it and/or modify     #
#  it under the terms of the GNU General Public License as published by     #
#  the Free Software Foundation version 3.                                  #
#                                                                           #
#  This program is distributed in the hope that it will be useful,          #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#  GNU General Public License for more details.                             #
#                                                                           #
#   You should have received a copy of the GNU General Public License       #
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.  #
#############################################################################

#
# Set toolchain.
# AVR-GCC and AVRDUDE need to be installed
#
CC = avr-gcc
OBJCOPY = avr-objcopy
AVRDUDE = avrdude
REMOVE = rm -f

#
# You probably want to change this to your own programming device.
# Some commonly used examples shown below.
#

# STK500
PGMDEV = stk500v2
PGMOPT = -P /dev/ttyS0


# AVR ISP mkII
#PGMDEV = avrispmkII
#PGMOPT = -P usb # Try   -B 10   in case of programming errors

# Pony-STK200
#PGMDEV = pony-stk200
#PGMOPT = -E noreset
